import Head from 'next/head'
import Image from 'next/image'
import ListProducts from '../comps/ListProducts';
import styles from '../styles/Home.module.css'

export const getStaticProps = async () => {
  const API_URL = `https://assessment-edvora.herokuapp.com`;
  const res = await fetch(API_URL);
  const products = await res.json();

  const productsByName = {};
  products.forEach(product => {
    const name = product.product_name;
    if(!productsByName[name]) {
      productsByName[name] = [];
    }
    productsByName[name].push(product);
  });
  return {
    props: { 
      products, 
      productsByName
    }
  }
}
export default function Home({products, productsByName}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>
        Edvora
      </h1>
      <p>Products</p>
      <main>
        {console.log(Object.values(productsByName))}
        {Object.values(productsByName).map( products => <ListProducts key={products[0].product_name} products={products} category={products[0].product_name}/>)}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Created by Mohamed Gad
        </a>
      </footer>
    </div>
  )
}
