import Head from 'next/head'
import Image from 'next/image'
import ListProducts from '../comps/ListProducts';
import styles from '../styles/Home.module.css'

export const getStaticProps = async () => {
  const API_URL = `https://assessment-edvora.herokuapp.com`;
  const res = await fetch(API_URL);
  const products = await res.json();

  const productsByName = {};
  const productsByState = {};
  const productsByCity = {};
  products.forEach(product => {
    const name = product.product_name;
    if (!productsByName[name]) {
      productsByName[name] = [];
    }
    productsByName[name].push(product);

    const state = product.address.state; 
    if (!productsByState[state]) {
      productsByState[state] = [];
    }
    productsByState[state].push(product);

    const city = product.address.city; 
    if (!productsByCity[city]) {
      productsByCity[city] = [];
    }
    productsByCity[city].push(product);

  });
  return {
    props: {
      products,
      productsByName,
      productsByState,
      productsByCity
    }
  }
}
export default function Home({ products, productsByName, productsByState, productsByCity }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <aside>
          <span>
            Filters
          </span>
          <ul>
            <li>
              Products
              <ul>
                {Object.keys(productsByName).map( name => <li key={name} >{name}</li>)}
              </ul>
            </li>
            <li>
              State
              <ul>
              {Object.keys(productsByState).map( name => <li key={name} >{name}</li>)}
              </ul>
            </li>
            <li>
              city
              <ul>
              {Object.keys(productsByCity).map( name => <li key={name} >{name}</li>)}
              </ul>
            </li>
          </ul>
        </aside>
        <div>
          <h1>
            Edvora
          </h1>
          <p>Products</p>
          {Object.values(productsByName).map(products => <ListProducts key={products[0].product_name} products={products} category={products[0].product_name} />)}
        </div>
      </main>
      <footer>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Created by Mohamed Gad
        </a>
      </footer>
    </div>
  )
}